export enum ConfigKeys{
    MSS_HOST = 'MSS_HOST',
    MSS_PORT= 'MSS_PORT',
    MSS_USERNAME = 'MSS_USERNAME',
    MSS_PASSWORD=  'MSS_PASSWORD',
    MSS_DATABASE= 'MSS_DATABASE' ,
    MSS_ENCRYPT= 'MSS_ENCRYPT',

    TYPE_ENTITIES= 'TYPE_ENTITIES',

    JWT_SECRET= 'JWT_SECRET',
    JWT_EXPIRATION= 'JWT_EXPIRATION',

    NODE_ENV= 'NODE_ENV',
    API_ROUTE= 'API_ROUTE', 
    API_SWAGGER= 'API_SWAGGER',
    PORT_API= 'PORT_API'
}